name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main 
      uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # pip install jupyter-book ghp-import


    # Build the book and Push the book's HTML to github-pages
    - name: build jupyter-book and copy book's HTML to the gh-pages branch
      run: |
        jupyter-book build ./    
        ghp-import -n -p -f _build/html     
